In [5]:
import pandas as pd

In [9]:
df = pd.read_csv('pandas/telco_churn.csv)
tempdict = {'col1':[1,2,3], 'col2':[4,5,6], 'col3':[7,8,9]}
dictdf = pd.DataFrame.from_dict(tempdict)

SyntaxError: unterminated string literal (detected at line 1) (2088539562.py, line 1)

In [7]:
df.tail()

NameError: name 'df' is not defined

In [8]:
df.columns

NameError: name 'df' is not defined

In [ ]:
df.dtypes

In [ ]:
df.describe()

In [39]:
df.describe(include='object')

       State International plan Voice mail plan  Churn
count   3333               3333            3333   3325
unique    51                  2               2      2
top       WV                 No              No  False
freq     106               3010            2411   2842

In [41]:
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [42]:
df['International plan']

0        No
1        No
2        No
3       Yes
4       Yes
       ...
3328     No
3329     No
3330     No
3331    Yes
3332     No
Name: International plan, Length: 3333, dtype: object

In [43]:
df[['State', 'International plan']]

     State International plan
0       KS                 No
1       OH                 No
2       NJ                 No
3       OH                Yes
4       OK                Yes
...    ...                ...
3328    AZ                 No
3329    WV                 No
3330    RI                 No
3331    CT                Yes
3332    TN                 No

[3333 rows x 2 columns]

In [45]:
df.Churn.unique

<bound method Series.unique of 0       False
1       False
2       False
3       False
4       False
        ...
3328    False
3329    False
3330    False
3331    False
3332    False
Name: Churn, Length: 3333, dtype: object>

In [46]:
df[df['International plan'] == 'No']

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
6,MA,121,510,No,Yes,24,218.2,88.0,37.09,348.5,108.0,29.62,212.6,118.0,9.57,7.5,7,2.03,3.0,NaN
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,SC,79,415,No,No,0,134.7,98.0,22.90,189.7,68.0,16.12,221.4,128.0,9.96,11.8,5,3.19,2.0,False
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [2]:
df[(df['international plan'] == 'No') & (df['Churn'] == False)]

NameError: name 'df' is not defined

In [ ]:
df.iloc[14]

In [ ]:
df.iloc[14, 0]

In [ ]:
state = df.copy()
state.set_index('State', implace=True)
state.head()

In [ ]:
state.loc['OH']

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna(implace=True)

In [ ]:
df.drop(''Area code', axis=1)

In [ ]:
df['New Column'] = df['Total night minutes'] + df['Total intl minutes']

In [ ]:
df.head()

In [ ]:
df['New Column'] = 100

In [ ]:
df.head()

In [ ]:
df.iloc[0,-1] = 10

In [ ]:
df.head()

In [ ]:
df['Churn Binary'] = df['Churn'].apply(lambda x: 1 if x = True else 0)

In [ ]:
df.head()

In [ ]:
df.to_csv('output.csv')

In [ ]:
df.to_json()

In [ ]:
df.to_html()

In [ ]:
del df